### ISSUE TITLE
LDAP listing is empty

### ISSUE THREAD

**Issue by dwgnr** [th-nuernberg/usermgmt#86]
The output of `usermgmt list` and `usermgmt list --simple-output-for-ldap true` is empty.

**Comment by BoolPurist** [comment]
Question: Was your database filled with any user while running your mentioned command ? The empty output only happens on my machine if the LDAP database is empty. 

In that case that makes sense to me because this output format is meant to be parseable for other programs. Empty means, there is no users to be listed.

**Comment by dwgnr** [comment]
Yeah, it was a query against the current prod database that definitely shouldn't be empty. Can you also try on prod and see if it works for you?

**Comment by BoolPurist** [comment]
Problem was resolved by specifying the field for "ldap_readonly_user_prefix" and "ldap_readonly_bind" within the configuration file "conf.toml".
